import type { ClassificationTaxonomy } from './taxonomy.ts';

const globalPrefix = 'JEVmail/';
export const DEFAULT_TAXONOMY: ClassificationTaxonomy = { labels: [
  { id:'reply_needed', displayName:'Reply Needed', description:'A legitimate person or organization is waiting for a response from you.', guidance:'Use when a reply is the primary required handling. Do not promote unsolicited sales or bulk outreach merely because it asks a question.', enabled:true, priority:10, semanticRole:'reply_needed', gmailLabelName:`${globalPrefix}Reply Needed` },
  { id:'action_needed', displayName:'Action Needed', description:'You need to do something, but replying is not the primary action.', guidance:'Examples: pay, sign, schedule, upload, review, complete a form, secure an account.', enabled:true, priority:20, semanticRole:'action_needed', gmailLabelName:`${globalPrefix}Action Needed` },
  { id:'reservation_confirmation', displayName:'Reservation / Confirmation', description:'A booking, appointment, ticket, registration, order confirmation, or similar reference item.', guidance:'Use only when no reply or action is required.', enabled:true, priority:30, semanticRole:'standard', gmailLabelName:`${globalPrefix}Reservation - Confirmation` },
  { id:'receipt_record', displayName:'Receipt / Record', description:'A receipt, paid invoice, statement, donation record, or other item mainly worth retaining.', guidance:'Use for records that generally can be archived after review and do not require action.', enabled:true, priority:40, semanticRole:'standard', gmailLabelName:`${globalPrefix}Receipt - Record` },
  { id:'account_security', displayName:'Account / Security Notice', description:'Security, login, device, password, privacy, or account-change notice that is mainly informational.', guidance:'If the notice requires the user to take protective action, classify Action Needed instead.', enabled:true, priority:50, semanticRole:'standard', gmailLabelName:`${globalPrefix}Account - Security` },
  { id:'verification_code', displayName:'Verification / One-Time Code', description:'Short-lived login, password reset, device verification, or one-time passcode message.', guidance:'Use when the message is transient and primarily supplies a code or verification link.', enabled:true, priority:60, semanticRole:'standard', gmailLabelName:`${globalPrefix}Verification - Code` },
  { id:'shipping_delivery', displayName:'Shipping / Delivery', description:'Tracking, shipment, delivery, pickup, or arrival status.', guidance:'Use when informational; if user action is required, classify Action Needed.', enabled:true, priority:70, semanticRole:'standard', gmailLabelName:`${globalPrefix}Shipping - Delivery` },
  { id:'fyi_no_action', displayName:'FYI / No Action', description:'Legitimate information worth seeing that requires neither response nor action.', guidance:'Use for meaningful informational mail that does not better fit a more specific retention category.', enabled:true, priority:80, semanticRole:'standard', gmailLabelName:`${globalPrefix}FYI - No Action` },
  { id:'radiology_medicine', displayName:'Radiology / Medicine', description:'Healthcare and medical mail, including professional clinical and radiology content.', guidance:'Use for all healthcare and medical mail: journals, digests, CME and meeting notices, case or imaging reports, hospital communications, even when formatted as a newsletter.', enabled:true, priority:85, semanticRole:'standard', gmailLabelName:`${globalPrefix}Radiology - Medicine` },
  { id:'newsletter_subscription', displayName:'Newsletter / Subscription', description:'Recurring informational or editorial bulk mail from a publication or subscription.', guidance:'Use for newsletters even when the subject includes calls to read or click.', enabled:true, priority:90, semanticRole:'standard', gmailLabelName:`${globalPrefix}Newsletter - Subscription` },
  { id:'cold_marketing', displayName:'Cold Marketing', description:'Unsolicited sales, vendor, recruiting, lead-generation, or promotional outreach.', guidance:'Use even if the sender asks for a meeting or reply when there is no established relationship or obligation.', enabled:true, priority:100, semanticRole:'standard', gmailLabelName:`${globalPrefix}Cold Marketing` },
  { id:'political', displayName:'Political', description:'Campaign, party, PAC, fundraising, advocacy, or political mobilization email.', guidance:'Use for political bulk mail unless a genuine prior relationship creates a higher-priority reply/action obligation.', enabled:true, priority:110, semanticRole:'standard', gmailLabelName:`${globalPrefix}Political` },
  { id:'indeterminate', displayName:'Indeterminate', description:'The message does not fit confidently into another enabled label.', guidance:'Use instead of inventing facts, especially when meaningful content is only in an unsupported attachment.', enabled:true, priority:999, semanticRole:'indeterminate', gmailLabelName:`${globalPrefix}Indeterminate` },
]};

export const DEFAULT_GLOBAL_INSTRUCTIONS = `Classify by required handling, not topic. Reply Needed outranks every other category when a legitimate conversational response is expected. Action Needed outranks every category except Reply Needed when the user must do something. Cold marketing and political bulk mail do not become Reply Needed merely because they ask a question. When no response or action is required, choose the best retention/triage category. If evidence is insufficient, choose Indeterminate.`;
