import type { GmailMessage,GmailPart } from './types.ts';
export type AttachmentMeta={filename:string;mimeType:string;size?:number};
export type NormalizedMessage={id:string;threadId:string;timestampMs:number;sender:string;recipients:string[];subject:string;body:string;attachments:AttachmentMeta[];labelIds:string[]};
function decode(data?:string){if(!data)return ''; try{return Buffer.from(data,'base64url').toString('utf8');}catch{return '';}}
function header(part:GmailPart|undefined,name:string){return part?.headers?.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value??'';}
function stripHtml(html:string){return html.replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<br\s*\/?>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'");}
function allParts(part:GmailPart|undefined):GmailPart[]{if(!part)return[]; return [part,...(part.parts??[]).flatMap(allParts)];}
function cleanBody(text:string){let out=text.replace(/\r/g,''); const markers=[/^On .+wrote:\s*$/m,/^From:\s.+$/m,/^-{2,}\s*Original Message\s*-{2,}$/mi]; let cut=out.length; for(const re of markers){const m=re.exec(out); if(m&&m.index<cut)cut=m.index;} out=out.slice(0,cut); out=out.replace(/^>.*$/gm,''); out=out.replace(/\n--\s*\n[\s\S]*$/m,''); out=out.replace(/[ \t]{2,}/g,' ').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim(); return out;}
export function normalizeGmailMessage(message:GmailMessage):NormalizedMessage {const parts=allParts(message.payload); const plain=parts.find(p=>p.mimeType==='text/plain'&&!p.filename); const html=parts.find(p=>p.mimeType==='text/html'&&!p.filename); const body=cleanBody(plain?decode(plain.body?.data):stripHtml(decode(html?.body?.data))); const attachments=parts.filter(p=>Boolean(p.filename)).map(p=>({filename:p.filename!,mimeType:p.mimeType??'application/octet-stream',size:p.body?.size})); const to=[header(message.payload,'To'),header(message.payload,'Cc')].filter(Boolean).join(',').split(',').map(x=>x.trim()).filter(Boolean); return {id:message.id,threadId:message.threadId,timestampMs:message.internalDate,sender:header(message.payload,'From'),recipients:to,subject:header(message.payload,'Subject'),body,attachments,labelIds:message.labelIds};}
